// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: raft.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RequestVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  int64                  `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   int64                  `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{1}
}

func (x *RequestVoteRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RequestVoteRequest) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RequestVoteResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex  int64                  `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   int64                  `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  int64                  `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEntriesRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesRequest) GetPrevLogIndex() int64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() int64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() int64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	MatchIndex    int64                  `protobuf:"varint,3,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{4}
}

func (x *AppendEntriesResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesResponse) GetMatchIndex() int64 {
	if x != nil {
		return x.MatchIndex
	}
	return 0
}

type SubmitEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitEntryRequest) Reset() {
	*x = SubmitEntryRequest{}
	mi := &file_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEntryRequest) ProtoMessage() {}

func (x *SubmitEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEntryRequest.ProtoReflect.Descriptor instead.
func (*SubmitEntryRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitEntryRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type SubmitEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Index         int64                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Term          int64                  `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitEntryResponse) Reset() {
	*x = SubmitEntryResponse{}
	mi := &file_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEntryResponse) ProtoMessage() {}

func (x *SubmitEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEntryResponse.ProtoReflect.Descriptor instead.
func (*SubmitEntryResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitEntryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubmitEntryResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *SubmitEntryResponse) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SubmitEntryResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *SubmitEntryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogRequest) Reset() {
	*x = QueryLogRequest{}
	mi := &file_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogRequest) ProtoMessage() {}

func (x *QueryLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogRequest.ProtoReflect.Descriptor instead.
func (*QueryLogRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{7}
}

type QueryLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CurrentTerm   int64                  `protobuf:"varint,4,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	CommitIndex   int64                  `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	LastApplied   int64                  `protobuf:"varint,6,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,7,rep,name=entries,proto3" json:"entries,omitempty"`
	State         map[string]string      `protobuf:"bytes,8,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogResponse) Reset() {
	*x = QueryLogResponse{}
	mi := &file_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogResponse) ProtoMessage() {}

func (x *QueryLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogResponse.ProtoReflect.Descriptor instead.
func (*QueryLogResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{8}
}

func (x *QueryLogResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *QueryLogResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *QueryLogResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *QueryLogResponse) GetCurrentTerm() int64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *QueryLogResponse) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *QueryLogResponse) GetLastApplied() int64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *QueryLogResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *QueryLogResponse) GetState() map[string]string {
	if x != nil {
		return x.State
	}
	return nil
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_raft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{9}
}

type EntryMetric struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Index               int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	SubmittedAtUnixNano int64                  `protobuf:"varint,2,opt,name=submitted_at_unix_nano,json=submittedAtUnixNano,proto3" json:"submitted_at_unix_nano,omitempty"`
	CommittedAtUnixNano int64                  `protobuf:"varint,3,opt,name=committed_at_unix_nano,json=committedAtUnixNano,proto3" json:"committed_at_unix_nano,omitempty"`
	AppliedAtUnixNano   int64                  `protobuf:"varint,4,opt,name=applied_at_unix_nano,json=appliedAtUnixNano,proto3" json:"applied_at_unix_nano,omitempty"`
	ApplyDelayNanos     int64                  `protobuf:"varint,5,opt,name=apply_delay_nanos,json=applyDelayNanos,proto3" json:"apply_delay_nanos,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EntryMetric) Reset() {
	*x = EntryMetric{}
	mi := &file_raft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryMetric) ProtoMessage() {}

func (x *EntryMetric) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryMetric.ProtoReflect.Descriptor instead.
func (*EntryMetric) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{10}
}

func (x *EntryMetric) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EntryMetric) GetSubmittedAtUnixNano() int64 {
	if x != nil {
		return x.SubmittedAtUnixNano
	}
	return 0
}

func (x *EntryMetric) GetCommittedAtUnixNano() int64 {
	if x != nil {
		return x.CommittedAtUnixNano
	}
	return 0
}

func (x *EntryMetric) GetAppliedAtUnixNano() int64 {
	if x != nil {
		return x.AppliedAtUnixNano
	}
	return 0
}

func (x *EntryMetric) GetApplyDelayNanos() int64 {
	if x != nil {
		return x.ApplyDelayNanos
	}
	return 0
}

type GetMetricsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	CurrentTerm    int64                  `protobuf:"varint,3,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	CommitIndex    int64                  `protobuf:"varint,4,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	LastApplied    int64                  `protobuf:"varint,5,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	ReplicationLag int64                  `protobuf:"varint,6,opt,name=replication_lag,json=replicationLag,proto3" json:"replication_lag,omitempty"`
	Metrics        []*EntryMetric         `protobuf:"bytes,7,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_raft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{11}
}

func (x *GetMetricsResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetMetricsResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetMetricsResponse) GetCurrentTerm() int64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *GetMetricsResponse) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *GetMetricsResponse) GetLastApplied() int64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *GetMetricsResponse) GetReplicationLag() int64 {
	if x != nil {
		return x.ReplicationLag
	}
	return 0
}

func (x *GetMetricsResponse) GetMetrics() []*EntryMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_raft_proto protoreflect.FileDescriptor

const file_raft_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"raft.proto\x12\x04raft\"N\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\"\x95\x01\n" +
	"\x12RequestVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x03R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x03R\vlastLogTerm\"L\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"\xe0\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x03 \x01(\x03R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x03R\vprevLogTerm\x12(\n" +
	"\aentries\x18\x05 \x03(\v2\x0e.raft.LogEntryR\aentries\x12#\n" +
	"\rleader_commit\x18\x06 \x01(\x03R\fleaderCommit\"f\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vmatch_index\x18\x03 \x01(\x03R\n" +
	"matchIndex\".\n" +
	"\x12SubmitEntryRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"\x86\x01\n" +
	"\x13SubmitEntryResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x03R\x05index\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x03R\x04term\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x11\n" +
	"\x0fQueryLogRequest\"\xe2\x02\n" +
	"\x10QueryLogResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12!\n" +
	"\fcurrent_term\x18\x04 \x01(\x03R\vcurrentTerm\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x03R\vcommitIndex\x12!\n" +
	"\flast_applied\x18\x06 \x01(\x03R\vlastApplied\x12(\n" +
	"\aentries\x18\a \x03(\v2\x0e.raft.LogEntryR\aentries\x127\n" +
	"\x05state\x18\b \x03(\v2!.raft.QueryLogResponse.StateEntryR\x05state\x1a8\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11GetMetricsRequest\"\xea\x01\n" +
	"\vEntryMetric\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x123\n" +
	"\x16submitted_at_unix_nano\x18\x02 \x01(\x03R\x13submittedAtUnixNano\x123\n" +
	"\x16committed_at_unix_nano\x18\x03 \x01(\x03R\x13committedAtUnixNano\x12/\n" +
	"\x14applied_at_unix_nano\x18\x04 \x01(\x03R\x11appliedAtUnixNano\x12*\n" +
	"\x11apply_delay_nanos\x18\x05 \x01(\x03R\x0fapplyDelayNanos\"\x80\x02\n" +
	"\x12GetMetricsResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12!\n" +
	"\fcurrent_term\x18\x03 \x01(\x03R\vcurrentTerm\x12!\n" +
	"\fcommit_index\x18\x04 \x01(\x03R\vcommitIndex\x12!\n" +
	"\flast_applied\x18\x05 \x01(\x03R\vlastApplied\x12'\n" +
	"\x0freplication_lag\x18\x06 \x01(\x03R\x0ereplicationLag\x12+\n" +
	"\ametrics\x18\a \x03(\v2\x11.raft.EntryMetricR\ametrics2\xdb\x02\n" +
	"\vRaftService\x12B\n" +
	"\vRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\x12H\n" +
	"\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12B\n" +
	"\vSubmitEntry\x12\x18.raft.SubmitEntryRequest\x1a\x19.raft.SubmitEntryResponse\x129\n" +
	"\bQueryLog\x12\x15.raft.QueryLogRequest\x1a\x16.raft.QueryLogResponse\x12?\n" +
	"\n" +
	"GetMetrics\x12\x17.raft.GetMetricsRequest\x1a\x18.raft.GetMetricsResponseB\x1aZ\x18project21/internal/pb;pbb\x06proto3"

var (
	file_raft_proto_rawDescOnce sync.Once
	file_raft_proto_rawDescData []byte
)

func file_raft_proto_rawDescGZIP() []byte {
	file_raft_proto_rawDescOnce.Do(func() {
		file_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)))
	})
	return file_raft_proto_rawDescData
}

var file_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_raft_proto_goTypes = []any{
	(*LogEntry)(nil),              // 0: raft.LogEntry
	(*RequestVoteRequest)(nil),    // 1: raft.RequestVoteRequest
	(*RequestVoteResponse)(nil),   // 2: raft.RequestVoteResponse
	(*AppendEntriesRequest)(nil),  // 3: raft.AppendEntriesRequest
	(*AppendEntriesResponse)(nil), // 4: raft.AppendEntriesResponse
	(*SubmitEntryRequest)(nil),    // 5: raft.SubmitEntryRequest
	(*SubmitEntryResponse)(nil),   // 6: raft.SubmitEntryResponse
	(*QueryLogRequest)(nil),       // 7: raft.QueryLogRequest
	(*QueryLogResponse)(nil),      // 8: raft.QueryLogResponse
	(*GetMetricsRequest)(nil),     // 9: raft.GetMetricsRequest
	(*EntryMetric)(nil),           // 10: raft.EntryMetric
	(*GetMetricsResponse)(nil),    // 11: raft.GetMetricsResponse
	nil,                           // 12: raft.QueryLogResponse.StateEntry
}
var file_raft_proto_depIdxs = []int32{
	0,  // 0: raft.AppendEntriesRequest.entries:type_name -> raft.LogEntry
	0,  // 1: raft.QueryLogResponse.entries:type_name -> raft.LogEntry
	12, // 2: raft.QueryLogResponse.state:type_name -> raft.QueryLogResponse.StateEntry
	10, // 3: raft.GetMetricsResponse.metrics:type_name -> raft.EntryMetric
	1,  // 4: raft.RaftService.RequestVote:input_type -> raft.RequestVoteRequest
	3,  // 5: raft.RaftService.AppendEntries:input_type -> raft.AppendEntriesRequest
	5,  // 6: raft.RaftService.SubmitEntry:input_type -> raft.SubmitEntryRequest
	7,  // 7: raft.RaftService.QueryLog:input_type -> raft.QueryLogRequest
	9,  // 8: raft.RaftService.GetMetrics:input_type -> raft.GetMetricsRequest
	2,  // 9: raft.RaftService.RequestVote:output_type -> raft.RequestVoteResponse
	4,  // 10: raft.RaftService.AppendEntries:output_type -> raft.AppendEntriesResponse
	6,  // 11: raft.RaftService.SubmitEntry:output_type -> raft.SubmitEntryResponse
	8,  // 12: raft.RaftService.QueryLog:output_type -> raft.QueryLogResponse
	11, // 13: raft.RaftService.GetMetrics:output_type -> raft.GetMetricsResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_raft_proto_init() }
func file_raft_proto_init() {
	if File_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_proto_goTypes,
		DependencyIndexes: file_raft_proto_depIdxs,
		MessageInfos:      file_raft_proto_msgTypes,
	}.Build()
	File_raft_proto = out.File
	file_raft_proto_goTypes = nil
	file_raft_proto_depIdxs = nil
}
